### ISSUE TITLE
Emoji Support

### ISSUE THREAD

**Issue by nicknikolov** [hironishihara/ofxTrueTypeFontUC#15]
Hi,

I'm trying to use your library to draw Emoji using Apple's Color Emoji ttf. Unfortunately I am getting this error:

[ error ] ofxTrueTypeFontUC::loadFont - Error with FT_Load_Glyph 112: FT_Error = 22

Code:
```c
// in setup
myFont.loadFont("Apple Color Emoji.ttf", 72);
// in draw
myFont.drawString("🐞", 100, 100);
```
Thanks in advance!

**Comment by hironishihara** [comment]
Hi,

Unfortunately ofxTrueTypeFontUC doesn't support Emoji.
Additionally there are no plans to support it in this addon.

I too need an alternative which supports Emoji.
I would like to create it in the near future.

**Comment by nicknikolov** [comment]
Hi Hiro,
I understand and thanks for the quick reply!
